/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


public class ApaDialogButton {
	private boolean enabled;
	private int label;
	private @ApaWarningAcknowledgment int ack;

	/**
	 * @param enabled
	 * @param label
	 * @param ack
	 */
	public ApaDialogButton(
		boolean enabled,
		int label,
		@ApaWarningAcknowledgment int ack
	) {
		this.enabled = enabled;
		this.label = label;
		this.ack = ack;
	}

	/**
	 * @param enabled
	 * @param label
	 */
	public ApaDialogButton(
		boolean enabled,
		int label
	) {
		this(enabled, label, ApaWarningAcknowledgment.ACK_1);
	}

	/** @param enabled */
	public ApaDialogButton(boolean enabled) {
		this(enabled, 0, ApaWarningAcknowledgment.ACK_1);
	}

	/** Constructs an instance with each member initialized to its default value */
	public ApaDialogButton() {
		this(false, 0, ApaWarningAcknowledgment.ACK_1);
	}

	public final boolean getEnabled() {
		return this.enabled;
	}

	public final int getLabel() {
		return this.label;
	}

	@ApaWarningAcknowledgment
	@NonNull
	public final int getAck() {
		return this.ack;
	}

	@Override
	@NonNull
	public String toString() {
		return "ApaDialogButton(" +
			"enabled=" + this.enabled + ", " +
			"label=" + this.label + ", " +
			"ack=" + this.ack + ")";
	}

	@Override
	public int hashCode() {
		return Objects.hash(
			this.enabled,
			this.label,
			this.ack);
	}

	@Override
	public boolean equals(@Nullable Object obj) {
		if (this == obj) {
			return true;
		} else {
			if (obj instanceof ApaDialogButton) {
				ApaDialogButton other = (ApaDialogButton) obj;
				return
					Objects.equals(this.enabled, other.enabled) &&
					Objects.equals(this.label, other.label) &&
					Objects.equals(this.ack, other.ack);
			}
			return false;
		}
	}
}

