/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/** DialogBox */
public class ApaDialogBox {
	private int label;
	private @NonNull ApaDialogButton positiveButton;
	private @NonNull ApaDialogButton neutralButton;
	private @NonNull ApaDialogButton negativeButton;

	/**
	 * @param label
	 * @param positiveButton
	 * @param neutralButton
	 * @param negativeButton
	 */
	public ApaDialogBox(
		int label,
		@NonNull ApaDialogButton positiveButton,
		@NonNull ApaDialogButton neutralButton,
		@NonNull ApaDialogButton negativeButton
	) {
		this.label = label;
		this.positiveButton = positiveButton;
		this.neutralButton = neutralButton;
		this.negativeButton = negativeButton;
	}

	/**
	 * @param label
	 * @param positiveButton
	 * @param neutralButton
	 */
	public ApaDialogBox(
		int label,
		@NonNull ApaDialogButton positiveButton,
		@NonNull ApaDialogButton neutralButton
	) {
		this(label, positiveButton, neutralButton, new ApaDialogButton());
	}

	/**
	 * @param label
	 * @param positiveButton
	 */
	public ApaDialogBox(
		int label,
		@NonNull ApaDialogButton positiveButton
	) {
		this(label, positiveButton, new ApaDialogButton(), new ApaDialogButton());
	}

	/** @param label */
	public ApaDialogBox(int label) {
		this(label, new ApaDialogButton(), new ApaDialogButton(), new ApaDialogButton());
	}

	/** Constructs an instance with each member initialized to its default value */
	public ApaDialogBox() {
		this(0, new ApaDialogButton(), new ApaDialogButton(), new ApaDialogButton());
	}

	public final int getLabel() {
		return this.label;
	}

	@NonNull
	public final ApaDialogButton getPositiveButton() {
		return this.positiveButton;
	}

	@NonNull
	public final ApaDialogButton getNeutralButton() {
		return this.neutralButton;
	}

	@NonNull
	public final ApaDialogButton getNegativeButton() {
		return this.negativeButton;
	}

	@Override
	@NonNull
	public String toString() {
		return "ApaDialogBox(" +
			"label=" + this.label + ", " +
			"positiveButton=" + this.positiveButton + ", " +
			"neutralButton=" + this.neutralButton + ", " +
			"negativeButton=" + this.negativeButton + ")";
	}

	@Override
	public int hashCode() {
		return Objects.hash(
			this.label,
			this.positiveButton,
			this.neutralButton,
			this.negativeButton);
	}

	@Override
	public boolean equals(@Nullable Object obj) {
		if (this == obj) {
			return true;
		} else {
			if (obj instanceof ApaDialogBox) {
				ApaDialogBox other = (ApaDialogBox) obj;
				return
					Objects.equals(this.label, other.label) &&
					Objects.equals(this.positiveButton, other.positiveButton) &&
					Objects.equals(this.neutralButton, other.neutralButton) &&
					Objects.equals(this.negativeButton, other.negativeButton);
			}
			return false;
		}
	}
}

