/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	ApaNavigationDisplayState.DISPLAY_NONE,
	ApaNavigationDisplayState.DISPLAY_HFP_SCANNING,
	ApaNavigationDisplayState.DISPLAY_HFP_PARKOUT_CONFIRMATION,
	ApaNavigationDisplayState.DISPLAY_HFP_GUIDANCE,
	ApaNavigationDisplayState.DISPLAY_FAPK_SCANNING,
	ApaNavigationDisplayState.DISPLAY_FAPK_GUIDANCE
})
/**
 * APA current navigation display state.
 *
 * - `display none` No display state or display state unavailable
 * - `display hfp scanning` Scanning display state
 * - `display hfp parkout confirmation` Parkout confirmation display state
 * - `display hfp guidance` Guidance display state
 * - `display fapk scanning` fapk scanning display state
 * - `display fapk guidance` fapk guidance display state
 */
public @interface ApaNavigationDisplayState {
	int DISPLAY_NONE = 0;
	int DISPLAY_HFP_SCANNING = 1;
	int DISPLAY_HFP_PARKOUT_CONFIRMATION = 2;
	int DISPLAY_HFP_GUIDANCE = 3;
	int DISPLAY_FAPK_SCANNING = 4;
	int DISPLAY_FAPK_GUIDANCE = 5;
}
