/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/apa-warnings.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/** Easy Park Assist (APA) navigation current state */
public interface IApaWarningViewModel {
	/** DialogBox to be displayed upon warning reception */
	@NonNull
	LiveData<ApaDialogBox> getDialogBox();

	/**
	 * Action to acknowledge a warning
	 *
	 * @param ack
	 */
	public void acknowledgeWarning(@ApaWarningAcknowledgment int ack);
}
