/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/apa-settings.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/**
 * Handles automatic park assist settings.
 *
 * _Automatic Parking Assist  - Feature ID : _
 */
public interface IApaSettingsViewModel {
	/** Display maneuver selector */
	boolean getManeuverSelectorVisible();

	/** Different types of maneuver that can be applied */
	@NonNull
	List<Integer> getManeuvers();

	/** Currently selected default maneuver mode. */
	@NonNull
	LiveData<Integer> getDefaultManeuver();

	/**
	 * Switch the default maneuver mode.
	 *
	 * @param mode the mode to set
	 */
	public void setDefaultManeuver(@Maneuver int mode);
}
