/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.camera;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/** Avm Camera preview sizes */
public class AvmCameraSize {
	private @NonNull CameraSize port;
	private @NonNull CameraSize land;

	/**
	 * @param port
	 * @param land
	 */
	public AvmCameraSize(
		@NonNull CameraSize port,
		@NonNull CameraSize land
	) {
		this.port = port;
		this.land = land;
	}

	/** @param port */
	public AvmCameraSize(@NonNull CameraSize port) {
		this(port, new CameraSize());
	}

	/** Constructs an instance with each member initialized to its default value */
	public AvmCameraSize() {
		this(new CameraSize(), new CameraSize());
	}

	@NonNull
	public final CameraSize getPort() {
		return this.port;
	}

	@NonNull
	public final CameraSize getLand() {
		return this.land;
	}

	@Override
	@NonNull
	public String toString() {
		return "AvmCameraSize(" +
			"port=" + this.port + ", " +
			"land=" + this.land + ")";
	}

	@Override
	public int hashCode() {
		return Objects.hash(
			this.port,
			this.land);
	}

	@Override
	public boolean equals(@Nullable Object obj) {
		if (this == obj) {
			return true;
		} else {
			if (obj instanceof AvmCameraSize) {
				AvmCameraSize other = (AvmCameraSize) obj;
				return
					Objects.equals(this.port, other.port) &&
					Objects.equals(this.land, other.land);
			}
			return false;
		}
	}
}

