/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.camera;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	CameraOverlay.NONE,
	CameraOverlay.RVC_STANDARD,
	CameraOverlay.RVC_SETTINGS,
	CameraOverlay.AVM_STANDARD,
	CameraOverlay.AVM_PANORAMIC,
	CameraOverlay.AVM_SIDES,
	CameraOverlay.AVM_3_D,
	CameraOverlay.AVM_POPUP,
	CameraOverlay.AVM_SETTINGS,
	CameraOverlay.AVM_APA,
	CameraOverlay.RVC_APA,
	CameraOverlay.TRAILER
})
/**
 * Camera overlay:
 * - `none` requests for an empty overlay view (i.e. dealer view)
 * - `rvc/avm_standard` requests for a standard view (bird + rear/front view)
 * - `avm_panoramic` requests for a panoramic view (rear or front panoramic view)
 * - `avm_sides` requests for a sides view
 * - `avm_3d` request for a 3D view
 * - `avm_popup` requests for a bird view (from top)
 * - 'settings' requests a settings view
 * - 'avm_apa' for an avm apa view (bird + rear/front view)
 * - 'rvc_apa' for an rvc apa view
 * - 'trailer' requests a trailer view
 * - 'error' requests an error view
 */
public @interface CameraOverlay {
	int NONE = 0;
	int RVC_STANDARD = 1;
	int RVC_SETTINGS = 2;
	int AVM_STANDARD = 3;
	int AVM_PANORAMIC = 4;
	int AVM_SIDES = 5;
	int AVM_3_D = 6;
	int AVM_POPUP = 7;
	int AVM_SETTINGS = 8;
	int AVM_APA = 9;
	int RVC_APA = 10;
	int TRAILER = 11;
}
