/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.camera;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/** Camera preview size */
public class CameraSize {
	private int width;
	private int height;

	/**
	 * @param width
	 * @param height
	 */
	public CameraSize(
		int width,
		int height
	) {
		this.width = width;
		this.height = height;
	}

	/** @param width */
	public CameraSize(int width) {
		this(width, 0);
	}

	/** Constructs an instance with each member initialized to its default value */
	public CameraSize() {
		this(0, 0);
	}

	public final int getWidth() {
		return this.width;
	}

	public final int getHeight() {
		return this.height;
	}

	@Override
	@NonNull
	public String toString() {
		return "CameraSize(" +
			"width=" + this.width + ", " +
			"height=" + this.height + ")";
	}

	@Override
	public int hashCode() {
		return Objects.hash(
			this.width,
			this.height);
	}

	@Override
	public boolean equals(@Nullable Object obj) {
		if (this == obj) {
			return true;
		} else {
			if (obj instanceof CameraSize) {
				CameraSize other = (CameraSize) obj;
				return
					Objects.equals(this.width, other.width) &&
					Objects.equals(this.height, other.height);
			}
			return false;
		}
	}
}

