################################################################################
# Gitlab CI Template
################################################################################
include:
  - project: 'partners/loire/hmi/devops/ci-templates'
    file: 'ci/pipeline.yml'