/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sound-settings.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sound;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/**
 * Control sound settings
 *
 * _Ultrasonic Parking Assist  - Feature ID : 10905_
 */
public interface ISoundSettingsViewModel {
	/** Whether the sound is enabled */
	@NonNull
	LiveData<Boolean> getSoundEnabled();

	/** Defines the id of the sound to use for sonar sound notifications */
	@NonNull
	LiveData<Integer> getSoundId();

	/** Sound volume */
	@NonNull
	LiveData<Integer> getVolume();

	/** Display sound activation switch */
	boolean getSoundSwitchVisible();

	/** Display volume selector */
	boolean getVolumeVisible();

	/** Display sound type selector */
	boolean getSoundTypeVisible();

	/** Min possible volume */
	int getMinVolume();

	/** Max possible volume */
	int getMaxVolume();

	/** Different types of sound that can be applied */
	@NonNull
	List<SoundDescriptor> getSounds();

	/**
	 * Activate or de-activate sonar sound
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableSound(boolean enable);

	/**
	 * Sets the sound type
	 *
	 * @param id the desired sound id
	 */
	public void setSound(int id);

	/**
	 * Sets the volume
	 *
	 * @param volume the volume to set
	 */
	public void setVolume(int volume);
}
