/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sound;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/** Simple object that represents the possible types of sound */
public class SoundDescriptor {
	private @NonNull String name;
	private int id;

	/**
	 * @param name The name given to that sound
	 * @param id The id of the sound
	 */
	public SoundDescriptor(
		@NonNull String name,
		int id
	) {
		this.name = name;
		this.id = id;
	}

	/** @param name The name given to that sound */
	public SoundDescriptor(@NonNull String name) {
		this(name, 0);
	}

	/** Constructs an instance with each member initialized to its default value */
	public SoundDescriptor() {
		this("", 0);
	}

	/** @return The name given to that sound */
	@NonNull
	public final String getName() {
		return this.name;
	}

	/** @return The id of the sound */
	public final int getId() {
		return this.id;
	}

	@Override
	@NonNull
	public String toString() {
		return "SoundDescriptor(" +
			"name=" + this.name + ", " +
			"id=" + this.id + ")";
	}

	@Override
	public int hashCode() {
		return Objects.hash(
			this.name,
			this.id);
	}

	@Override
	public boolean equals(@Nullable Object obj) {
		if (this == obj) {
			return true;
		} else {
			if (obj instanceof SoundDescriptor) {
				SoundDescriptor other = (SoundDescriptor) obj;
				return
					Objects.equals(this.name, other.name) &&
					Objects.equals(this.id, other.id);
			}
			return false;
		}
	}
}

