/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sonar-alerts.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/**
 * Handles Rear Cross Traffic Alert state.
 *
 * _Rear Cross Traffic Alert
 */
public interface ISonarAlertsViewModel {
	/** If left RCTA flag should be visible */
	@NonNull
	LiveData<Boolean> getRctaLeftVisible();

	/** If right RCTA flag should be visible */
	@NonNull
	LiveData<Boolean> getRctaRightVisible();

	/** If RAEB flags should be visible */
	@NonNull
	LiveData<Boolean> getRaebVisible();
}
