/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sonar-state.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/**
 * Control parking sensors activation and report
 * collision detection information.
 *
 * _Ultrasonic Parking Assist  - Feature ID : 10905_
 */
public interface ISonarStateViewModel {
	/** Front left UPA Sensor state */
	@NonNull
	LiveData<ParkingSensor> getFrontLeft();

	/** Front center UPA Sensor state */
	@NonNull
	LiveData<ParkingSensor> getFrontCenter();

	/** Front right UPA Sensor state */
	@NonNull
	LiveData<ParkingSensor> getFrontRight();

	/** Rear left UPA Sensor state */
	@NonNull
	LiveData<ParkingSensor> getRearLeft();

	/** Rear center UPA Sensor state */
	@NonNull
	LiveData<ParkingSensor> getRearCenter();

	/** Rear right UPA Sensor state */
	@NonNull
	LiveData<ParkingSensor> getRearRight();

	/** Left front FKP Sensor state */
	@NonNull
	LiveData<ParkingSensor> getLeftFront();

	/** Left front-center FKP Sensor state */
	@NonNull
	LiveData<ParkingSensor> getLeftFrontCenter();

	/** Left rear-center FKP Sensor state */
	@NonNull
	LiveData<ParkingSensor> getLeftRearCenter();

	/** Left rear FKP Sensor state */
	@NonNull
	LiveData<ParkingSensor> getLeftRear();

	/** Right front FKP Sensor state */
	@NonNull
	LiveData<ParkingSensor> getRightFront();

	/** Right front-center FKP Sensor state */
	@NonNull
	LiveData<ParkingSensor> getRightFrontCenter();

	/** Right rear-center FKP Sensor state */
	@NonNull
	LiveData<ParkingSensor> getRightRearCenter();

	/** Right rear FKP Sensor state */
	@NonNull
	LiveData<ParkingSensor> getRightRear();

	/** Whether an obstacle has been detected on the vehicle path */
	@NonNull
	LiveData<Boolean> getObstacle();

	/** Whether front sensors are enabled */
	@NonNull
	LiveData<Boolean> getFrontEnabled();

	/** Whether rear sensors are enabled */
	@NonNull
	LiveData<Boolean> getRearEnabled();

	/** Whether flank sensors are enabled */
	@NonNull
	LiveData<Boolean> getFlankEnabled();

	/** Whether car avatar should be displayed */
	@NonNull
	LiveData<Boolean> getAvatarVisible();

	/** Close camera view action visible */
	@NonNull
	LiveData<Boolean> getCloseVisible();

	/**
	 * Activate or de-activate front sensors
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableFront(boolean enable);

	/**
	 * Activate or de-activate rear sensors
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableRear(boolean enable);

	/**
	 * Activate or de-activate flank sensors
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableFlank(boolean enable);
}
