/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sonar-mute-state.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/**
 * Control parking sensors activation and report
 * collision detection information.
 *
 * _Ultrasonic Parking Assist  - Feature ID : 10905_
 */
public interface ISonarMuteStateViewModel {
	/** Whether Sonar Sound is muted or not */
	@NonNull
	LiveData<Boolean> getMuted();

	/** Mute button visibility */
	@NonNull
	LiveData<Boolean> getVisible();

	/**
	 * Mute or Unmute Sonar Sound
	 *
	 * @param muted true to mute, false to unmute
	 */
	public void mute(boolean muted);
}
