/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sonar-settings.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/**
 * Control parking sensors activation
 *
 * _Ultrasonic Parking Assist  - Feature ID : 10905_
 */
public interface ISonarSettingsViewModel {
	/** Whether front sensors are enabled */
	@NonNull
	LiveData<Boolean> getFrontEnabled();

	/** Whether front sensors are visible */
	boolean getFrontVisible();

	/** Whether rear sensors are enabled */
	@NonNull
	LiveData<Boolean> getRearEnabled();

	/** Whether rear sensors are visible */
	boolean getRearVisible();

	/** Whether rear sensors are (de)activable */
	boolean getRearToggleVisible();

	/** Whether flank sensors are enabled */
	@NonNull
	LiveData<Boolean> getFlankEnabled();

	/** Whether flank sensors are visible */
	boolean getFlankVisible();

	/** Whether OSE is enabled */
	@NonNull
	LiveData<Boolean> getOseEnabled();

	/** Whether OSE is visible */
	boolean getOseVisible();

	/** Whether RCTA is enabled */
	@NonNull
	LiveData<Boolean> getRctaEnabled();

	/** Whether RCTA option is visible */
	boolean getRctaVisible();

	/** Whether R-AEB is enabled */
	@NonNull
	LiveData<Boolean> getRaebEnabled();

	/** Whether R-AEB is visible */
	boolean getRaebVisible();

	/**
	 * Activate or de-activate front sensors
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableFront(boolean enable);

	/**
	 * Activate or de-activate rear sensors
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableRear(boolean enable);

	/**
	 * Activate or de-activate flank sensors
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableFlank(boolean enable);

	/**
	 * Activate or de-activate OSE
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableOse(boolean enable);

	/**
	 * Activate or de-activate RCTA
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableRcta(boolean enable);

	/**
	 * Activate or de-activate R-AEB
	 *
	 * @param enable true to enable, false to disable
	 */
	public void enableRaeb(boolean enable);
}
