/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sonar-full.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/** Handles Sonar Alert Visibility. */
public interface ISonarFullViewModel {
	/** If sonar alert should be visible */
	@NonNull
	LiveData<Boolean> getSonarAlertVisibility();

	/** EasyPark indication */
	@NonNull
	LiveData<Boolean> getEasyParkIndication();

	/**
	 * Change sonar alert visibility
	 *
	 * @param visible true to show, false to hide
	 */
	public void setSonarAlertVisibility(boolean visible);
}
