/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v1.5.1.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	RctaSide.NONE,
	RctaSide.LEFT,
	RctaSide.RIGHT,
	RctaSide.LEFT_RIGHT
})
/** Where the obstacle is coming from */
public @interface RctaSide {
	int NONE = 0;
	int LEFT = 1;
	int RIGHT = 2;
	int LEFT_RIGHT = 3;
}
