/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/hfp-parkout-vehicle-center.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa.hfp;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/** Easy Park Assist (APA) guidance state */
public interface IHfpParkoutVehicleCenterViewModel {
	/** Whether the left double curve is visible */
	@NonNull
	LiveData<Boolean> getLeftDoubleCurveVisible();

	/** Whether the right double curve is visible */
	@NonNull
	LiveData<Boolean> getRightDoubleCurveVisible();

	/** Whether the stop is visible */
	@NonNull
	LiveData<Boolean> getStopVisible();

	/** Whether the arrow right side is visible */
	@NonNull
	LiveData<Boolean> getArrowRightSideVisible();

	/** Whether the arrow left side is visible */
	@NonNull
	LiveData<Boolean> getArrowLeftSideVisible();
}
