/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/hfp-guidance-vehicle-center-cut.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa.hfp;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/** Easy Park Assist (APA) guidance state */
public interface IHfpGuidanceVehicleCenterCutViewModel {
	/** Whether the arrow curve down is visible */
	@NonNull
	LiveData<Boolean> getArrowCurveDownVisible();

	/** Whether the engage left active is visible */
	@NonNull
	LiveData<Boolean> getEngageLeftActiveVisible();

	/** Whether the engage left not active is visible */
	@NonNull
	LiveData<Boolean> getEngageLeftNotActiveVisible();

	/** Whether the engage right is active */
	@NonNull
	LiveData<Boolean> getEngageRightActiveVisible();

	/** Whether the engage right is not active */
	@NonNull
	LiveData<Boolean> getEngageRightNotActiveVisible();
}
