/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/hfp-guidance-vehicle-center.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa.hfp;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/** Easy Park Assist (APA) guidance state */
public interface IHfpGuidanceVehicleCenterViewModel {
	/** Whether the arrow Straight Up is visible */
	@NonNull
	LiveData<Boolean> getArrowStraightUpVisible();

	/** Whether the arrow Curve Up is visible */
	@NonNull
	LiveData<Boolean> getArrowCurveUpVisible();

	/** Whether the engage front is active */
	@NonNull
	LiveData<Boolean> getEngageFrontActiveVisible();

	/** Whether the engage front is not active */
	@NonNull
	LiveData<Boolean> getEngageFrontNotActiveVisible();

	/** Whether the frontright curve is active */
	@NonNull
	LiveData<Boolean> getRightCurveFrontActiveVisible();

	/** Whether the frontright curve is not active */
	@NonNull
	LiveData<Boolean> getRightCurveFrontNotActiveVisible();

	/** Whether the frontleft curve is active */
	@NonNull
	LiveData<Boolean> getLeftCurveFrontActiveVisible();

	/** Whether the frontleft curve is not active */
	@NonNull
	LiveData<Boolean> getLeftCurveFrontNotActiveVisible();

	/** Whether the arrow Straight Down is visible */
	@NonNull
	LiveData<Boolean> getArrowStraightDownVisible();

	/** Whether the arrow Curve Down is visible */
	@NonNull
	LiveData<Boolean> getArrowCurveDownVisible();

	/** Whether the engage back is active */
	@NonNull
	LiveData<Boolean> getEngageBackActiveVisible();

	/** Whether the engage back is not active */
	@NonNull
	LiveData<Boolean> getEngageBackNotActiveVisible();

	/** Whether the backright curve is active */
	@NonNull
	LiveData<Boolean> getRightCurveBackActiveVisible();

	/** Whether the backright curve is not active */
	@NonNull
	LiveData<Boolean> getRightCurveBackNotActiveVisible();

	/** Whether the backleft curve is active */
	@NonNull
	LiveData<Boolean> getLeftCurveBackActiveVisible();

	/** Whether the backleft curve is not active */
	@NonNull
	LiveData<Boolean> getLeftCurveBackNotActiveVisible();

	/** Whether the left double curve is visible */
	@NonNull
	LiveData<Boolean> getLeftDoubleCurveVisible();

	/** Whether the right double curve is visible */
	@NonNull
	LiveData<Boolean> getRightDoubleCurveVisible();

	/** Whether the stop is visible */
	@NonNull
	LiveData<Boolean> getStopVisible();
}
