/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/hfp-guidance-vehicle-center-front.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa.hfp;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/** Easy Park Assist (APA) guidance state */
public interface IHfpGuidanceVehicleCenterFrontViewModel {
	/** Whether the arrow straight up is visible */
	@NonNull
	LiveData<Boolean> getArrowStraightUpVisible();

	/** Whether the engage front is active */
	@NonNull
	LiveData<Boolean> getEngageFrontActiveVisible();

	/** Whether the engage front is not active */
	@NonNull
	LiveData<Boolean> getEngageFrontNotActiveVisible();

	/** Whether the stop front is visible */
	@NonNull
	LiveData<Boolean> getStopFrontVisible();
}
