/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/hfp-parkout.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa.hfp;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.LiveData;
import java.util.List;

/** Easy Park Assist (APA) parkout confirmation illustration */
public interface IHfpParkoutViewModel {
	/** Whether the background Sides is visible */
	@NonNull
	LiveData<Boolean> getBackgroundSidesVisible();

	/** Whether the background Parallel Left is visible */
	@NonNull
	LiveData<Boolean> getBackgroundParallelLeftVisible();

	/** Whether the vehicle center is visible with parallel left background */
	@NonNull
	LiveData<Boolean> getParallelLeftVehicleCenterVisible();

	/** Whether the background Parallel Right is visible */
	@NonNull
	LiveData<Boolean> getBackgroundParallelRightVisible();

	/** Whether the vehicle center is visible with parallel right background */
	@NonNull
	LiveData<Boolean> getParallelRightVehicleCenterVisible();

	/** Whether the vehicle left is visible with parallel left background */
	@NonNull
	LiveData<Boolean> getParallelLeftVehicleLeftVisible();

	/** Whether the vehicle right is visible with parallel right background */
	@NonNull
	LiveData<Boolean> getParallelRightVehicleRightVisible();
}
