//=================================================================================
// DO NOT EDIT THIS FILE, IT WILL BE AUTOMATICALLY SYNC-ED FROM AndroidAppTemplate.
//=================================================================================
@file:Suppress("UNUSED_VARIABLE")

import org.jetbrains.dokka.gradle.DokkaMultiModuleTask

plugins {
    id("nebula.dependency-lock")
    id("org.jetbrains.dokka")
}

tasks.withType<DokkaMultiModuleTask>().configureEach {
    // add readme
    includes.from(listOf("README.md").filter { file(it).exists() })

    // set output directories
    if (name == "dokkaHtmlMultiModule") outputDirectory.set(buildDir.resolve("html/docs"))
    if (name == "dokkaGfmMultiModule") outputDirectory.set(buildDir.resolve("gfm/docs"))
    if (name == "dokkaJavadocMultiModule") outputDirectory.set(buildDir.resolve("javadoc/docs"))
    if (name == "dokkaJekyllMultiModule") outputDirectory.set(buildDir.resolve("jekyll/docs"))

    removeChildTasks(subprojects.filter {
        !it.path.startsWith(":module")
    })
}

tasks {
    // clean up task
    val clean: TaskProvider<Task> by registering {
        delete("$buildDir")
    }
}
