/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.sonar;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	UpaDisplayRequestType.NO_DISPLAY,
	UpaDisplayRequestType.REAR,
	UpaDisplayRequestType.FRONT,
	UpaDisplayRequestType.REAR_FRONT
})
/** UPA display request type */
public @interface UpaDisplayRequestType {
	int NO_DISPLAY = 0;
	int REAR = 1;
	int FRONT = 2;
	int REAR_FRONT = 3;
}
