package com.renault.parkassist.repository.routing

enum class PlatformRouteIdentifier {
    SURROUND_MAIN,
    SURROUND_TRAILER,
    SURROUND_SETTINGS,
    SURROUND_DEALER,
    SURROUND_POPUP,
    SURROUND_CLOSED,
    SURROUND_WARNING,
    SURROUND_WARNING_CLOSED,
    SURROUND_FAPK,
    SONAR_REAR,
    SONAR_NOT_REAR,
    SONAR_CLOSED,
    PARKING_SCANNING,
    PARKING_GUIDANCE,
    PARKING_PARK_OUT,
    PARKING_CLOSED,
    PARKING_WARNING,
    PARKING_WARNING_CLOSED
}