/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.avm;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	AvmModeSelected.STANDARD,
	AvmModeSelected.PANORAMIC,
	AvmModeSelected.SIDES,
	AvmModeSelected.THREE_D
})
/**
 * AVM video current display mode selected
 * - `standard` Standard view avm selected
 * - `panoramic` Panoramic view selected
 * - `sides` Sides view selected
 * - `three-d` Three-d view selected
 */
public @interface AvmModeSelected {
	int STANDARD = 0;
	int PANORAMIC = 1;
	int SIDES = 2;
	int THREE_D = 3;
}
