/**
 * This is a generated file: do not modify.
 * <p>
 * Generated by midl v2.1.0.
 * <p>
 * Copyright (c) 2019 Renault SW Labs
 * <p>
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.surroundview;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
    Action.CLOSE_VIEW,
    Action.ACTIVATE_MANEUVER_VIEW,
    Action.ACTIVATE_SETTINGS_VIEW,
    Action.ACTIVATE_TRAILER_VIEW,
    Action.SELECT_PANORAMIC_VIEW,
    Action.SELECT_STANDARD_VIEW,
    Action.SELECT_SIDES_VIEW,
    Action.SELECT_THREE_DIMENSION_VIEW,
    Action.SELECT_FRONT_CAMERA,
    Action.SELECT_REAR_CAMERA,
    Action.BACK_FROM_SETTINGS_VIEW,
    Action.SELECT_LEFT_CAMERA,
    Action.SELECT_RIGHT_CAMERA
})
public @interface Action {
    int CLOSE_VIEW = 0;
    int ACTIVATE_MANEUVER_VIEW = 1;
    int ACTIVATE_SETTINGS_VIEW = 2;
    int ACTIVATE_TRAILER_VIEW = 3;
    int SELECT_PANORAMIC_VIEW = 4;
    int SELECT_STANDARD_VIEW = 5;
    int SELECT_SIDES_VIEW = 6;
    int SELECT_THREE_DIMENSION_VIEW = 7;
    int SELECT_FRONT_CAMERA = 8;
    int SELECT_REAR_CAMERA = 9;
    int BACK_FROM_SETTINGS_VIEW = 10;
    int SELECT_LEFT_CAMERA = 11;
    int SELECT_RIGHT_CAMERA = 12;
}
