/**
 * This is a generated file: do not modify.
 * <p>
 * Generated by midl v2.1.0.
 * <p>
 * Copyright (c) 2019 Renault SW Labs
 * <p>
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.surroundview;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
    FeatureConfig.RVC,
    FeatureConfig.AVM,
    FeatureConfig.NONE,
    FeatureConfig.MVC
})
/** Type of surround view hardware present in the vehicle. */
public @interface FeatureConfig {
    int RVC = 0;
    int AVM = 1;
    int NONE = 2;
    int MVC = 3;
}
