/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.surroundview;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	Origin.REQUEST_FROM_VEHICLE,
	Origin.REQUEST_FROM_CLIENT,
	Origin.NO_REQUEST
})
public @interface Origin {
	int REQUEST_FROM_VEHICLE = 0;
	int REQUEST_FROM_CLIENT = 1;
	int NO_REQUEST = 2;
}
