/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.surroundview;

import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * State representation of surroundView service.
 * if isRequest is true, the state is currently request, else the state is established
 */
public class SurroundState {
	private @View int view;
	private boolean isRequest;

	/**
	 * @param view
	 * @param isRequest
	 */
	public SurroundState(
		@View int view,
		boolean isRequest
	) {
		this.view = view;
		this.isRequest = isRequest;
	}

	/** @param view */
	public SurroundState(@View int view) {
		this(view, false);
	}

	/** Constructs an instance with each member initialized to its default value */
	public SurroundState() {
		this(View.NO_DISPLAY, false);
	}

	@View
	@NonNull
	public final int getView() {
		return this.view;
	}

	public final boolean getIsRequest() {
		return this.isRequest;
	}

	@Override
	@NonNull
	public String toString() {
		return "SurroundState(" +
			"view=" + this.view + ", " +
			"isRequest=" + this.isRequest + ")";
	}

	@Override
	public int hashCode() {
		return Objects.hash(
			this.view,
			this.isRequest);
	}

	@Override
	public boolean equals(@Nullable Object obj) {
		if (this == obj) {
			return true;
		} else {
			if (obj instanceof SurroundState) {
				SurroundState other = (SurroundState) obj;
				return
					Objects.equals(this.view, other.view) &&
					Objects.equals(this.isRequest, other.isRequest);
			}
			return false;
		}
	}
}

