/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.surroundview;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	TrunkState.TRUNK_DOOR_STATE_UNAVAILABLE,
	TrunkState.TRUNK_DOOR_OPENED,
	TrunkState.TRUNK_DOOR_CLOSED
})
public @interface TrunkState {
	int TRUNK_DOOR_STATE_UNAVAILABLE = 0;
	int TRUNK_DOOR_OPENED = 1;
	int TRUNK_DOOR_CLOSED = 2;
}
