/**
 * This is a generated file: do not modify.
 * <p>
 * Generated by midl v2.1.0.
 * <p>
 * Copyright (c) 2019 Renault SW Labs
 * <p>
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.surroundview;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
    View.NO_DISPLAY,
    View.REAR_VIEW,
    View.FRONT_VIEW,
    View.PANORAMIC_REAR_VIEW,
    View.PANORAMIC_FRONT_VIEW,
    View.SIDES_VIEW,
    View.THREE_DIMENSION_VIEW,
    View.POP_UP_VIEW,
    View.DEALER_VIEW,
    View.AUTO_ZOOM_REAR_VIEW,
    View.TRAILER_VIEW,
    View.SETTINGS_REAR_VIEW,
    View.SETTINGS_FRONT_VIEW,
    View.APA_FRONT_VIEW,
    View.APA_REAR_VIEW,
    View.LEFT_VIEW,
    View.RIGHT_VIEW,
    View.SETTINGS_LEFT_VIEW,
    View.SETTINGS_RIGHT_VIEW
})
public @interface View {
    int NO_DISPLAY = 0;
    int REAR_VIEW = 1;
    int FRONT_VIEW = 2;
    int PANORAMIC_REAR_VIEW = 3;
    int PANORAMIC_FRONT_VIEW = 4;
    int SIDES_VIEW = 5;
    int THREE_DIMENSION_VIEW = 6;
    int POP_UP_VIEW = 7;
    int DEALER_VIEW = 8;
    int AUTO_ZOOM_REAR_VIEW = 9;
    int TRAILER_VIEW = 10;
    int SETTINGS_REAR_VIEW = 11;
    int SETTINGS_FRONT_VIEW = 12;
    int APA_FRONT_VIEW = 13;
    int APA_REAR_VIEW = 14;
    int LEFT_VIEW = 15;
    int RIGHT_VIEW = 16;
    int SETTINGS_LEFT_VIEW = 17;
    int SETTINGS_RIGHT_VIEW = 18;
}