/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sonar-alerts.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar.mock;


import android.app.Application;
import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.MutableLiveData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.renault.parkassist.viewmodel.sonar.SonarAlertsViewModelBase;

public class SonarAlertsViewModelMock extends SonarAlertsViewModelBase {
	public SonarAlertsViewModelMock(@NonNull Application application) {
		super(application);
		this.reset();
	}

	public void reset() {
		rctaLeftVisible.setValue(false);
		rctaRightVisible.setValue(false);
		raebVisible.setValue(false);
	}

	public void postReset() {
		rctaLeftVisible.postValue(false);
		rctaRightVisible.postValue(false);
		raebVisible.postValue(false);
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getRctaLeftVisible() {
		return rctaLeftVisible;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getRctaRightVisible() {
		return rctaRightVisible;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getRaebVisible() {
		return raebVisible;
	}

	protected MutableLiveData<Boolean> rctaLeftVisible = new MutableLiveData<>();
	protected MutableLiveData<Boolean> rctaRightVisible = new MutableLiveData<>();
	protected MutableLiveData<Boolean> raebVisible = new MutableLiveData<>();

	


}
