/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sonar-mute-state.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar.mock;


import android.app.Application;
import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.MutableLiveData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.renault.parkassist.viewmodel.sonar.SonarMuteStateViewModelBase;

public class SonarMuteStateViewModelMock extends SonarMuteStateViewModelBase {
	public SonarMuteStateViewModelMock(@NonNull Application application) {
		super(application);
		this.reset();
	}

	public void reset() {
		muted.setValue(false);
		visible.setValue(false);
	}

	public void postReset() {
		muted.postValue(false);
		visible.postValue(false);
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getMuted() {
		return muted;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getVisible() {
		return visible;
	}

	protected MutableLiveData<Boolean> muted = new MutableLiveData<>();
	protected MutableLiveData<Boolean> visible = new MutableLiveData<>();

	

	@Override
	public void mute(boolean muted) {}
}
