/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/sonar-settings.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.sonar.mock;


import android.app.Application;
import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.MutableLiveData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.renault.parkassist.viewmodel.sonar.SonarSettingsViewModelBase;

public class SonarSettingsViewModelMock extends SonarSettingsViewModelBase {
	public SonarSettingsViewModelMock(@NonNull Application application) {
		super(application);
		this.reset();
	}

	public void reset() {
		frontEnabled.setValue(false);
		frontVisible = false;
		rearEnabled.setValue(false);
		rearVisible = false;
		rearToggleVisible = false;
		flankEnabled.setValue(false);
		flankVisible = false;
		oseEnabled.setValue(false);
		oseVisible = false;
		rctaEnabled.setValue(false);
		rctaVisible = false;
		raebEnabled.setValue(false);
		raebVisible = false;
	}

	public void postReset() {
		frontEnabled.postValue(false);
		frontVisible = false;
		rearEnabled.postValue(false);
		rearVisible = false;
		rearToggleVisible = false;
		flankEnabled.postValue(false);
		flankVisible = false;
		oseEnabled.postValue(false);
		oseVisible = false;
		rctaEnabled.postValue(false);
		rctaVisible = false;
		raebEnabled.postValue(false);
		raebVisible = false;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getFrontEnabled() {
		return frontEnabled;
	}

	@Override
	public boolean getFrontVisible() {
		return frontVisible;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getRearEnabled() {
		return rearEnabled;
	}

	@Override
	public boolean getRearVisible() {
		return rearVisible;
	}

	@Override
	public boolean getRearToggleVisible() {
		return rearToggleVisible;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getFlankEnabled() {
		return flankEnabled;
	}

	@Override
	public boolean getFlankVisible() {
		return flankVisible;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getOseEnabled() {
		return oseEnabled;
	}

	@Override
	public boolean getOseVisible() {
		return oseVisible;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getRctaEnabled() {
		return rctaEnabled;
	}

	@Override
	public boolean getRctaVisible() {
		return rctaVisible;
	}

	@NonNull
	@Override
	public MutableLiveData<Boolean> getRaebEnabled() {
		return raebEnabled;
	}

	@Override
	public boolean getRaebVisible() {
		return raebVisible;
	}

	protected MutableLiveData<Boolean> frontEnabled = new MutableLiveData<>();
	public boolean frontVisible;
	protected MutableLiveData<Boolean> rearEnabled = new MutableLiveData<>();
	public boolean rearVisible;
	public boolean rearToggleVisible;
	protected MutableLiveData<Boolean> flankEnabled = new MutableLiveData<>();
	public boolean flankVisible;
	protected MutableLiveData<Boolean> oseEnabled = new MutableLiveData<>();
	public boolean oseVisible;
	protected MutableLiveData<Boolean> rctaEnabled = new MutableLiveData<>();
	public boolean rctaVisible;
	protected MutableLiveData<Boolean> raebEnabled = new MutableLiveData<>();
	public boolean raebVisible;

	

	@Override
	public void enableFront(boolean enable) {}

	@Override
	public void enableRear(boolean enable) {}

	@Override
	public void enableFlank(boolean enable) {}

	@Override
	public void enableOse(boolean enable) {}

	@Override
	public void enableRcta(boolean enable) {}

	@Override
	public void enableRaeb(boolean enable) {}
}
