/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.surround;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	SurroundWarningType.SPEED_NOK,
	SurroundWarningType.CAMERA_SOILED,
	SurroundWarningType.CAMERA_MISALIGNED,
	SurroundWarningType.OBSTACLE_DETECTED,
	SurroundWarningType.TRAILER_ACCESS_LIMITED,
	SurroundWarningType.TRAILER_NOT_DETECTED,
	SurroundWarningType.NONE
})
/** Type of warning to display to the user. */
public @interface SurroundWarningType {
	int SPEED_NOK = 0;
	int CAMERA_SOILED = 1;
	int CAMERA_MISALIGNED = 2;
	int OBSTACLE_DETECTED = 3;
	int TRAILER_ACCESS_LIMITED = 4;
	int TRAILER_NOT_DETECTED = 5;
	int NONE = 6;
}
