/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0 from 'ParkAssist/vm-specification/apa-warnings.ts'.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.viewmodel.apa.mock;


import android.app.Application;
import androidx.annotation.FloatRange;
import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.Size;
import androidx.lifecycle.MutableLiveData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.renault.parkassist.viewmodel.apa.ApaWarningViewModelBase;

import com.renault.parkassist.viewmodel.apa.ApaDialogBox;
import com.renault.parkassist.viewmodel.apa.ApaDialogButton;
import com.renault.parkassist.viewmodel.apa.ApaWarningAcknowledgment;
import com.renault.parkassist.viewmodel.apa.ApaWarningMessage;

public class ApaWarningViewModelMock extends ApaWarningViewModelBase {
	public ApaWarningViewModelMock(@NonNull Application application) {
		super(application);
		this.reset();
	}

	public void reset() {
		dialogBox.setValue(new ApaDialogBox());
	}

	public void postReset() {
		dialogBox.postValue(new ApaDialogBox());
	}

	@NonNull
	@Override
	public MutableLiveData<ApaDialogBox> getDialogBox() {
		return dialogBox;
	}

	protected MutableLiveData<ApaDialogBox> dialogBox = new MutableLiveData<>();

	

	@Override
	public void acknowledgeWarning(@ApaWarningAcknowledgment int ack) {}
}
