import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

//=================================================================================
// DO NOT EDIT THIS FILE, IT WILL BE AUTOMATICALLY SYNC-ED FROM AndroidAppTemplate.
//=================================================================================
// import org.gradle.kotlin.dsl.`kotlin-dsl`
// import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    `kotlin-dsl`
    kotlin("jvm") version "1.5.21"
    id("com.diffplug.gradle.spotless") version "5.16.0" apply false
}

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}

repositories {
    maven { url= uri ("https://plugins.gradle.org/m2/")}
    google()
    mavenCentral()
}

dependencies {

    implementation("com.gladed.androidgitversion:gradle-android-git-version:0.4.14")

    // Kotlin
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32")

    // AGP
    implementation("com.android.tools.build:gradle:7.0.3")
    implementation("com.android.tools.build:gradle-api:7.0.3")

    // Dokka
    implementation ("org.jetbrains.dokka:dokka-gradle-plugin:1.5.30")

    // Detekt
    implementation("io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.18.1")

    // Spotless
    implementation("com.diffplug.spotless:spotless-plugin-gradle:5.16.0")

    // Jacoco
    implementation("org.jacoco:org.jacoco.core:0.8.7")

    // Artifactory
    implementation("org.jfrog.buildinfo:build-info-extractor-gradle:4.24.19")

    // Nebula
    implementation("com.netflix.nebula:gradle-dependency-lock-plugin:12.0.0")
}



