/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.apa;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	FeatureConfig.NONE,
	FeatureConfig.HFP,
	FeatureConfig.HFPB,
	FeatureConfig.FPK,
	FeatureConfig.FAPK
})
/**
 * Auto Park Assist vehicle configuration
 * - `none` no auto-park assist available
 * - `hfp` hands-free parking available
 * - `hfpb` auto-break hands-free parking available
 * - `fpk`  full park ??? available ** FIXME **
 * - `fapk` full auto-park available
 */
public @interface FeatureConfig {
	int NONE = 0;
	int HFP = 1;
	int HFPB = 2;
	int FPK = 3;
	int FAPK = 4;
}
