/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.apa;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	Instruction.SELECT_SIDE,
	Instruction.DRIVE_FORWARD_TO_FIND_PARKING_SLOT,
	Instruction.DRIVE_FORWARD_SLOT_SUITABLE,
	Instruction.STOP,
	Instruction.SELECT_REVERSE_GEAR_OR_PRESS_START_BUTTON,
	Instruction.SELECT_OR_ENGAGE_FORWARD_GEAR,
	Instruction.DRIVE_FORWARD,
	Instruction.REVERSE,
	Instruction.MANEUVER_COMPLETE_OR_FINISHED,
	Instruction.GO_FORWARD_OR_REVERSE,
	Instruction.MANEUVER_FINISHED_TAKE_BACK_CONTROL,
	Instruction.ENGAGE_REAR_GEAR,
	Instruction.STOP_AFTER_REAR_GEAR_ENGAGED,
	Instruction.ACCELERATE_AND_HOLD_THE_PEDAL_PRESSED,
	Instruction.MANEUVER_FINISHED_RELEASE_THE_ACCELERATOR_PEDAL,
	Instruction.HOLD_THE_ACCELERATOR_PEDAL_PRESSED,
	Instruction.STAND_BY_NO_TEXT,
	Instruction.UNAVAILABLE
})
public @interface Instruction {
	int SELECT_SIDE = 0;
	int DRIVE_FORWARD_TO_FIND_PARKING_SLOT = 1;
	int DRIVE_FORWARD_SLOT_SUITABLE = 2;
	int STOP = 3;
	int SELECT_REVERSE_GEAR_OR_PRESS_START_BUTTON = 4;
	int SELECT_OR_ENGAGE_FORWARD_GEAR = 5;
	int DRIVE_FORWARD = 6;
	int REVERSE = 7;
	int MANEUVER_COMPLETE_OR_FINISHED = 8;
	int GO_FORWARD_OR_REVERSE = 9;
	int MANEUVER_FINISHED_TAKE_BACK_CONTROL = 10;
	int ENGAGE_REAR_GEAR = 11;
	int STOP_AFTER_REAR_GEAR_ENGAGED = 12;
	int ACCELERATE_AND_HOLD_THE_PEDAL_PRESSED = 13;
	int MANEUVER_FINISHED_RELEASE_THE_ACCELERATOR_PEDAL = 14;
	int HOLD_THE_ACCELERATOR_PEDAL_PRESSED = 15;
	int STAND_BY_NO_TEXT = 16;
	int UNAVAILABLE = 17;
}
