/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.apa;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	ManeuverType.PARALLEL,
	ManeuverType.PERPENDICULAR,
	ManeuverType.ANGLED,
	ManeuverType.PARKOUT,
	ManeuverType.AUTO_MODE,
	ManeuverType.UNAVAILABLE
})
/**
 * Auto Park Assist maneuver types
 * - `parallel` park in parallel
 * - `perpendicular` park in perpendicular
 * - `angled` park in angled
 * - `parkout` park out
 * - `auto mode` apa selects automatically the maneuver
 * - `unavailable` no maneuver move
 */
public @interface ManeuverType {
	int PARALLEL = 0;
	int PERPENDICULAR = 1;
	int ANGLED = 2;
	int PARKOUT = 3;
	int AUTO_MODE = 4;
	int UNAVAILABLE = 5;
}
