/**
 * This is a generated file: do not modify.
 *
 * Generated by midl v2.1.0.
 *
 * Copyright (c) 2019 Renault SW Labs
 *
 * Developed by Renault SW Labs, an affiliate of RENAULT S.A.S. which holds all
 * intellectual property rights. Use of this software is subject to a specific
 * license granted by RENAULT S.A.S.
 */
package com.renault.parkassist.repository.apa;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import androidx.annotation.IntDef;

@Retention(RetentionPolicy.SOURCE)
@IntDef({
	ManeuverStartSwitch.NONE,
	ManeuverStartSwitch.UNUSABLE_START,
	ManeuverStartSwitch.DISPLAY_START,
	ManeuverStartSwitch.DISPLAY_START_AUTO_MODE,
	ManeuverStartSwitch.DISPLAY_START_PARALLEL,
	ManeuverStartSwitch.DISPLAY_START_PERPENDICULAR,
	ManeuverStartSwitch.DISPLAY_START_PARKOUT,
	ManeuverStartSwitch.DISPLAY_CANCEL
})
/**
 * Auto Park Assist maneuver start switch
 *
 * - 'none' maneuver start switch is not displayed or is unavailable
 * - 'unusable start' maneuver start switch is displayed as start but is not enabled
 * - 'display start' maneuver start switch is enabled and displayed as start
 * - 'display start' Maneuver start switch is enabled and displayed as start (auto mode)
 * - 'display start parallel' maneuver start switch is enabled and displayed as start (parallel mode)
 * - 'display start perpendicular' maneuver start switch is enabled and displayed as start (perpendicular mode)
 * - 'display start parkout' maneuver start switch is enabled and displayed as start (park out mode)
 * - 'display cancel' maneuver start switch is enabled and displayed as cancel
 */
public @interface ManeuverStartSwitch {
	int NONE = 0;
	int UNUSABLE_START = 1;
	int DISPLAY_START = 2;
	int DISPLAY_START_AUTO_MODE = 3;
	int DISPLAY_START_PARALLEL = 4;
	int DISPLAY_START_PERPENDICULAR = 5;
	int DISPLAY_START_PARKOUT = 6;
	int DISPLAY_CANCEL = 7;
}
